context:
  version: "0.1.7.5"
  python_min: "3.12"

package:
  name: dyno
  version: ${{ version }}

source:
  url: https://github.com/EconForge/dyno.py/archive/v${{ version }}.tar.gz
  sha256: 473e9d0a14b82e9a84c222e727b3c74b22e6b3540a8e9809450167b7a533360e

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:

  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip

  run:
    - python >=${{ python_min }}
    - numpy
    - pandas
    - pyyaml
    - lark
    - interegular
    - vega_datasets
    - tempita
    - sympy
    - altair
    - rich
    - typing_extensions
    - plotly
    - scipy
    - dynare-preprocessor-pylib

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - dyno
        
about:
  homepage: https://github.com/EconForge/dyno.py
  summary: A simple library for solving dynamic stochastic economic models.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albop
