context:
  version: "0.1.13"
  python_min: "3.12"

package:
  name: dyno
  version: ${{ version }}

source:
  url: https://github.com/EconForge/dyno.py/archive/v${{ version }}.tar.gz
  sha256: dc0f18a6a4b5a099dfc4507d8a74183b537772a4e97657bfdc2e0a5c076a8ba7

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:

  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip

  run:
    - python >=${{ python_min }},<3.14
    - altair >=5.0.0,<7
    - interegular >=0.3.3,<0.4
    - lark >=1.1.7,<2
    - markdown-it-py >=3.0.0,<5
    - mdit-py-plugins >=0.4.0,<1
    - numpy >=1.26.0,<3
    - pandas >=2.1.1,<4
    - plotext >=5.3.2,<6
    - pyyaml >=6.0,<7
    - rich >=13.0.0,<15
    - scipy >=1.11.3,<2
    - tempita >=0.6.0,<0.7
    - typing_extensions >=4.6.0,<5
    - dynare-preprocessor-pylib

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "3.13.*"
      imports:
        - dyno

about:
  homepage: https://github.com/EconForge/dyno.py
  summary: A simple library for solving dynamic stochastic economic models.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albop
